# Generated by Django 3.1.4 on 2020-12-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Protein Name')),
                ('accession', models.CharField(blank=True, max_length=25, verbose_name='NCBI accession number')),
                ('partnerprotein', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('partnerprotein_textbox', models.CharField(blank=True, max_length=250)),
                ('target_order', models.CharField(blank=True, max_length=250)),
                ('target_species', models.CharField(blank=True, max_length=250, null=True)),
                ('activity', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('taxonid', models.CharField(blank=True, max_length=25)),
                ('lc50', models.CharField(blank=True, max_length=25)),
                ('units', models.CharField(blank=True, max_length=25)),
                ('percentage_mortality', models.CharField(blank=True, max_length=25)),
                ('publication', models.TextField(blank=True)),
                ('stage', models.CharField(blank=True, max_length=75)),
                ('assay_material', models.TextField(blank=True)),
                ('assay_method', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('data_entered_by', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
