# Generated by Django 3.1.4 on 2020-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='accession',
            field=models.CharField(blank=True, max_length=25, verbose_name='NCBI accession number'),
        ),
    ]
