# Generated by Django 3.1.4 on 2021-02-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='non_toxic',
        ),
    ]
