# Generated by Django 3.1.4 on 2021-05-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_auto_20210503_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='assay_material',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='assay_method',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='data_entered_by',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='instar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='lc50',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='life_stage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='non_toxic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='other_citations',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='percentage_mortality',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='publication',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='target_order',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='target_species',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='taxonid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='units',
            field=models.TextField(null=True),
        ),
    ]
