# Generated by Django 3.1.4 on 2021-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("association", "0005_auto_20210503_2140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="association",
            name="partnerprotein",
            field=models.CharField(default="No", max_length=255),
        ),
    ]
