# Generated by Django 3.2.3 on 2021-05-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_auto_20210512_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'verbose_name': 'Meta database', 'verbose_name_plural': 'Specificity Metadatabase'},
        ),
    ]
