# Generated by Django 3.1.4 on 2021-05-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLinks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("link", models.TextField()),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
