# Generated by Django 3.1.4 on 2021-05-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extra", "0003_externallinks_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExternalLinks",
            new_name="Links",
        ),
    ]
