# Generated by Django 3.1.3 on 2021-06-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_alter_links_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact_status',
            field=models.CharField(choices=[('emailed', 'Emailed'), ('pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
