# Generated by Django 2.2.6 on 2020-08-18 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0005_auto_20200515_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded'),
        ),
    ]
