# Generated by Django 2.2.6 on 2019-10-31 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PesticidalProteinDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('oldname', models.CharField(blank=True, max_length=105)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('fastasequence', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('fastasequence_file', models.FileField(blank=True, null=True, upload_to='fastasequence_files/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProteinDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('fastasequence', models.TextField(blank=True)),
                ('fulllength', models.TextField(blank=True)),
                ('position_N', models.TextField(blank=True)),
                ('domain_N', models.TextField(blank=True)),
                ('pfam_N', models.TextField(blank=True)),
                ('position_M', models.TextField(blank=True)),
                ('domain_M', models.TextField(blank=True)),
                ('pfam_M', models.TextField(blank=True)),
                ('position_C', models.TextField(blank=True)),
                ('domain_C', models.TextField(blank=True)),
                ('pfam_C', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=None, max_length=40)),
                ('name', models.CharField(blank=True, max_length=15)),
                ('fastasequence', models.TextField(blank=True)),
            ],
        ),
    ]
