# Generated by Django 2.2.6 on 2020-05-10 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=75)),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesticidalProteinDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('oldname', models.CharField(blank=True, max_length=105)),
                ('othernames', models.TextField(blank=True)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('sequence', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('fastasequence_file', models.FileField(blank=True, null=True, upload_to='fastasequence_files/')),
                ('name_category', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PesticidalProteinPrivateDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('oldname', models.CharField(blank=True, max_length=105)),
                ('othernames', models.TextField(blank=True)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('sequence', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('fastasequence_file', models.FileField(blank=True, null=True, upload_to='fastasequence_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('sequence', models.TextField(blank=True)),
                ('fulllength', models.TextField(blank=True)),
                ('species', models.TextField(blank=True)),
                ('taxon', models.TextField(blank=True)),
                ('domain_N', models.TextField(blank=True)),
                ('pfam_N', models.CharField(blank=True, max_length=25)),
                ('cdd_N', models.CharField(blank=True, max_length=25)),
                ('start_N', models.CharField(blank=True, max_length=10)),
                ('end_N', models.CharField(blank=True, max_length=10)),
                ('domain_M', models.TextField(blank=True)),
                ('pfam_M', models.CharField(blank=True, max_length=25)),
                ('cdd_M', models.CharField(blank=True, max_length=25)),
                ('start_M', models.CharField(blank=True, max_length=10)),
                ('end_M', models.CharField(blank=True, max_length=10)),
                ('domain_C', models.TextField(blank=True)),
                ('pfam_C', models.CharField(blank=True, max_length=25)),
                ('cdd_C', models.CharField(blank=True, max_length=10)),
                ('start_C', models.CharField(blank=True, max_length=10)),
                ('end_C', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=None, max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('sequence', models.TextField(null=True)),
            ],
        ),
    ]
