# Generated by Django 3.1.3 on 2020-11-03 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OldnameNewnameTableLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_2020', models.CharField(blank=True, max_length=250)),
                ('name_1998', models.CharField(blank=True, max_length=250)),
                ('alternative_name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Oldname Newname Table Left Side',
            },
        ),
        migrations.CreateModel(
            name='OldnameNewnameTableRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1998', models.CharField(blank=True, max_length=250)),
                ('name_2020', models.CharField(blank=True, max_length=250)),
                ('alternative_name', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Oldname Newname Table Right Side',
            },
        ),
        migrations.CreateModel(
            name='PesticidalProteinDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('oldname', models.CharField(blank=True, max_length=105)),
                ('othernames', models.TextField(blank=True)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('sequence', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('fastasequence_file', models.FileField(blank=True, null=True, upload_to='fastasequence_files/')),
                ('name_category', models.CharField(blank=True, max_length=15)),
                ('public', models.BooleanField(default=True)),
                ('pdbcode', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Public Sequences',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PesticidalProteinHiddenSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('oldname', models.CharField(blank=True, max_length=105)),
                ('othernames', models.TextField(blank=True)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('sequence', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('fastasequence_file', models.FileField(blank=True, null=True, upload_to='fastasequence_files/')),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Hidden sequences for naming purpose',
            },
        ),
        migrations.CreateModel(
            name='ProteinDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('sequence', models.TextField(blank=True)),
                ('fulllength', models.TextField(blank=True)),
                ('species', models.TextField(blank=True)),
                ('taxon', models.TextField(blank=True)),
                ('domain_N', models.TextField(blank=True)),
                ('pfam_N', models.CharField(blank=True, max_length=25)),
                ('cdd_N', models.CharField(blank=True, max_length=25)),
                ('start_N', models.CharField(blank=True, max_length=10)),
                ('end_N', models.CharField(blank=True, max_length=10)),
                ('domain_M', models.TextField(blank=True)),
                ('pfam_M', models.CharField(blank=True, max_length=25)),
                ('cdd_M', models.CharField(blank=True, max_length=25)),
                ('start_M', models.CharField(blank=True, max_length=10)),
                ('end_M', models.CharField(blank=True, max_length=10)),
                ('domain_C', models.TextField(blank=True)),
                ('pfam_C', models.CharField(blank=True, max_length=25)),
                ('cdd_C', models.CharField(blank=True, max_length=10)),
                ('start_C', models.CharField(blank=True, max_length=10)),
                ('end_C', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Three domains data',
            },
        ),
        migrations.CreateModel(
            name='StructureDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('oldname', models.CharField(blank=True, max_length=75)),
                ('accession', models.CharField(blank=True, max_length=75)),
                ('pdbid', models.CharField(blank=True, max_length=25)),
                ('chimeric', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('pubmedid', models.CharField(blank=True, max_length=75)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Structure Database',
            },
        ),
        migrations.CreateModel(
            name='UserUploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=None, max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('sequence', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesticidalProteinPrivateDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('oldname', models.CharField(blank=True, max_length=105)),
                ('othernames', models.TextField(blank=True)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('sequence', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('fastasequence_file', models.FileField(blank=True, null=True, upload_to='fastasequence_files/')),
                ('public', models.BooleanField(default=False)),
                ('private', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('submittersname', models.CharField(blank=True, max_length=25, null=True)),
                ('submittersemail', models.EmailField(max_length=70, null=True)),
                ('bacterium', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('bacterium_textbox', models.CharField(blank=True, max_length=250, null=True)),
                ('taxonid', models.CharField(blank=True, max_length=25, null=True)),
                ('partnerprotein', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('partnerprotein_textbox', models.CharField(blank=True, max_length=250, null=True)),
                ('toxicto', models.CharField(blank=True, max_length=250)),
                ('nontoxic', models.CharField(blank=True, max_length=250)),
                ('dnasequence', models.TextField(null=True)),
                ('pdbcode', models.CharField(blank=True, max_length=10)),
                ('publication', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Private Sequences',
            },
        ),
    ]
