# Generated by Django 2.2.6 on 2019-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteindetail',
            old_name='position_C',
            new_name='species',
        ),
        migrations.RenameField(
            model_name='proteindetail',
            old_name='position_M',
            new_name='taxon',
        ),
        migrations.RemoveField(
            model_name='proteindetail',
            name='position_N',
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='cdd_C',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='cdd_M',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='cdd_N',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='end_C',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='end_M',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='end_N',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='start_C',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='start_M',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proteindetail',
            name='start_N',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_C',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_M',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='proteindetail',
            name='pfam_N',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
