# Generated by Django 3.1.3 on 2020-11-30 21:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldnamenewnametableleft',
            options={'verbose_name': 'Organized by new name', 'verbose_name_plural': 'Organized by new name'},
        ),
        migrations.AlterModelOptions(
            name='oldnamenewnametableright',
            options={'verbose_name': 'Organized by Oldname', 'verbose_name_plural': 'Organized by Oldname'},
        ),
        migrations.RemoveField(
            model_name='structuredatabase',
            name='chimeric',
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='admin_user',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='bacterium',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='bacterium_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='dnasequence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='nontoxic',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='partnerprotein',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='partnerprotein_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='submittersemail',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='submittersname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='terms_conditions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='toxicto',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='admin_user',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='alignresults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='bacterium',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='bacterium_textbox',
            field=models.CharField(default='Bacillus Thuringiensis', max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='dnasequence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='family',
            field=models.CharField(default='None', max_length=305),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='mammalian_active',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='nontoxic',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='partnerprotein',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='partnerprotein_textbox',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='pdbcode',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='private',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='strain',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='submittersemail',
            field=models.EmailField(default='None', max_length=70),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='submittersname',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='taxonid',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='terms_conditions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='pesticidalproteinhiddensequence',
            name='toxicto',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='alignresults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='name_category',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='terms_conditions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='structuredatabase',
            name='modified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='accession',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='name',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='year',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='pdbid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
