# Generated by Django 3.1.4 on 2020-12-14 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteindatabase_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteindatabase_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='edited_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Edited on'),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='published',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteinprivatedatabase_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteinprivatedatabase_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='edited_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Edited on'),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='published',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
