# Generated by Django 3.1.4 on 2020-12-14 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_auto_20201214_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='published',
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='created_by',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteinprivatedatabase_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
