# Generated by Django 3.1.4 on 2020-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201209_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='sequence',
            field=models.TextField(blank=True, verbose_name='Protein Sequence'),
        ),
    ]
