# Generated by Django 2.2.6 on 2020-08-13 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0002_oldnamenewnametableleft_oldnamenewnametableright'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldnamenewnametableleft',
            options={'verbose_name_plural': 'OldnameNewnameTableLeft'},
        ),
        migrations.AlterModelOptions(
            name='oldnamenewnametableright',
            options={'verbose_name_plural': 'OldnameNewnameTableRight'},
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='user',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
