# Generated by Django 2.2.6 on 2020-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191120_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=75)),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
