# Generated by Django 3.1.3 on 2020-11-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201103_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuredatabase',
            old_name='chimeric',
            new_name='modified',
        ),
    ]
