# Generated by Django 3.1.3 on 2020-12-01 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20201130_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='pdbid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000), default=list, size=None),
        ),
    ]
