# Generated by Django 2.2 on 2020-10-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20201019_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StructureDatabase',
        ),
    ]
