# Generated by Django 3.1.3 on 2020-11-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20201103_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='pdbid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
