# Generated by Django 3.1.3 on 2020-12-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20201201_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesticidalproteindatabase',
            old_name='comment',
            new_name='user_comment',
        ),
    ]
