# Generated by Django 2.2.6 on 2020-01-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_feedbackdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticidalproteindatabase',
            name='fastasequence',
        ),
    ]
