# Generated by Django 3.1.4 on 2020-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20201209_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='accession',
            field=models.CharField(blank=True, max_length=25, verbose_name='NCBI accession number'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='User comments'),
        ),
    ]
