# Generated by Django 2.2.6 on 2020-08-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200813_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldnamenewnametableleft',
            options={'verbose_name_plural': 'Oldname Newname Table Left Side'},
        ),
        migrations.AlterModelOptions(
            name='oldnamenewnametableright',
            options={'verbose_name_plural': 'Oldname Newname Table Right Side'},
        ),
        migrations.RenameField(
            model_name='pesticidalproteinprivatedatabase',
            old_name='user',
            new_name='admin_user',
        ),
    ]
