# Generated by Django 3.2.3 on 2021-05-31 14:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0004_auto_20210507_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticidalproteinhiddensequence',
            name='private',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinhiddensequence',
            name='toxicto',
        ),
        migrations.RemoveField(
            model_name='pesticidalproteinprivatedatabase',
            name='private',
        ),
        migrations.AlterField(
            model_name='oldnamenewnametableleft',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oldnamenewnametableleft',
            name='name_1998',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oldnamenewnametableleft',
            name='name_2020',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oldnamenewnametableright',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oldnamenewnametableright',
            name='name_1998',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='oldnamenewnametableright',
            name='name_2020',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='User comments'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteindatabase_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='dnasequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteindatabase_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='edited_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Edited on'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='name_category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='nontoxic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='oldname',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='othernames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='pdbcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='published',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersemail',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersname',
            field=models.CharField(blank=True, default='Uploaded by default admin user', max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('\\d{25}', 'Number must digits', 'Invalid number')]),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='terms_conditions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='toxicto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='accession',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='bacterium_textbox',
            field=models.CharField(blank=True, default='Bacillus Thuringiensis', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='dnasequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='family',
            field=models.CharField(blank=True, default='None', max_length=305, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='mammalian_active',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='nontoxic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='oldname',
            field=models.CharField(blank=True, max_length=305, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='othernames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='partnerprotein_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='pdbcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='sequence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='strain',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='submittersemail',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='submittersname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('\\d{25}', 'Number must digits', 'Invalid number')]),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='terms_conditions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Uploaded'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='alignresults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='bacterium_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='User comments'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteinprivatedatabase_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='dnasequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesticidalproteinprivatedatabase_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='edited_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Edited on'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='name_category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='nontoxic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='oldname',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='partnerprotein',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='partnerprotein_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='pdbcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='submittersemail',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='submittersname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('\\d{25}', 'Number must digits', 'Invalid number')]),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='terms_conditions',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='toxicto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Uploaded'),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='accession',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='modified',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='oldname',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='pubmedid',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
