# Generated by Django 2.2.6 on 2020-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200814_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='bacterium',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='bacterium_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='dnasequence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='nontoxic',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='partnerprotein',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='partnerprotein_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='pdbcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='submittersemail',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='submittersname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='toxicto',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
