# Generated by Django 3.1.4 on 2020-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201209_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='dnasequence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersemail',
            field=models.EmailField(blank=True, default='suresh.pannersel@ufl.edu', max_length=70),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersname',
            field=models.CharField(blank=True, default='Uploaded by Suresh', max_length=125),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='accession',
            field=models.CharField(blank=True, max_length=25, verbose_name='NCBI accession number'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='User comments'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Protein Name'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='sequence',
            field=models.TextField(blank=True, verbose_name='Protein Sequence'),
        ),
    ]
