# Generated by Django 2.2 on 2020-10-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_delete_structuredatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('oldname', models.CharField(blank=True, max_length=75)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('pdbid', models.CharField(blank=True, max_length=25)),
                ('pubmedid', models.CharField(blank=True, max_length=15)),
                ('year', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
