# Generated by Django 2.2.6 on 2020-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_pesticidalproteindatabase_fastasequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='fastasequence',
            field=models.TextField(blank=True),
        ),
    ]
