# Generated by Django 3.1.3 on 2020-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201103_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='pdbid',
            field=models.JSONField(blank=True, max_length=500),
        ),
    ]
