# Generated by Django 3.1.3 on 2020-12-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20201202_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesticidalproteindatabase',
            old_name='user_comment',
            new_name='comment',
        ),
    ]
