# Generated by Django 3.1.4 on 2020-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20201202_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersname',
            field=models.CharField(default='Neil', max_length=125),
        ),
    ]
