# Generated by Django 3.1.3 on 2020-11-23 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0005_auto_20201104_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='admin_user',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='bacterium',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='bacterium_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='dnasequence',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='nontoxic',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='partnerprotein',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='partnerprotein_textbox',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='submittersemail',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='submittersname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='taxonid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='terms_conditions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='toxicto',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='alignresults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='name_category',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='terms_conditions',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
