# Generated by Django 2.2 on 2020-10-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_structuredatabase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldnamenewnametableleft',
            options={'verbose_name_plural': 'Oldname Newname Table Left Side'},
        ),
        migrations.AlterModelOptions(
            name='oldnamenewnametableright',
            options={'verbose_name_plural': 'Oldname Newname Table Right Side'},
        ),
        migrations.AlterModelOptions(
            name='pesticidalproteindatabase',
            options={'ordering': ('name',), 'verbose_name_plural': 'Public Sequences'},
        ),
        migrations.AlterModelOptions(
            name='pesticidalproteinhiddensequence',
            options={'verbose_name_plural': 'Hidden sequences for naming purpose'},
        ),
        migrations.AlterModelOptions(
            name='pesticidalproteinprivatedatabase',
            options={'verbose_name_plural': 'Private Sequences'},
        ),
        migrations.AlterModelOptions(
            name='proteindetail',
            options={'verbose_name_plural': 'Three domains data'},
        ),
        migrations.AlterModelOptions(
            name='structuredatabase',
            options={'verbose_name_plural': 'Structure Database'},
        ),
    ]
