# Generated by Django 3.1.4 on 2020-12-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20201209_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersemail',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
