# Generated by Django 3.1.3 on 2020-11-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20201123_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldnamenewnametableleft',
            options={'verbose_name': 'Organized by new name', 'verbose_name_plural': 'Organized by new name'},
        ),
        migrations.AlterModelOptions(
            name='oldnamenewnametableright',
            options={'verbose_name': 'Organized by Oldname', 'verbose_name_plural': 'Organized by Oldname'},
        ),
    ]
