# Generated by Django 3.1.4 on 2020-12-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20201209_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='family',
            field=models.CharField(blank=True, default='None', max_length=305),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='mammalian_active',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='nontoxic',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='pdbcode',
            field=models.CharField(blank=True, default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinhiddensequence',
            name='toxicto',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
    ]
