# Generated by Django 2.2.6 on 2020-08-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200820_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesticidalproteinprivatedatabase',
            old_name='public',
            new_name='private',
        ),
    ]
