# Generated by Django 2.2 on 2020-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20201022_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredatabase',
            name='chimeric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='structuredatabase',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
