# Generated by Django 3.1.4 on 2020-12-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20201203_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='dnasequence',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersemail',
            field=models.EmailField(default='suresh.pannersel@ufl.edu', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='submittersname',
            field=models.CharField(default='Uploaded by Suresh', max_length=125),
        ),
    ]
