# Generated by Django 3.1.3 on 2021-06-03 14:57

import database.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_pesticidalproteinhiddensequence_toxicto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidalproteindatabase',
            name='fastasequence_file',
            field=models.FileField(null=True, storage=database.storage.OverwriteStorage(), upload_to='fastasequence_files/'),
        ),
    ]
