# Generated by Django 3.1.4 on 2020-12-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20201215_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesticidalproteindatabase',
            options={'ordering': ('name',), 'verbose_name': 'Public Sequence', 'verbose_name_plural': 'Public Sequences'},
        ),
        migrations.AlterModelOptions(
            name='pesticidalproteinhiddensequence',
            options={'verbose_name': 'Hidden sequence', 'verbose_name_plural': 'Hidden sequences for naming purpose'},
        ),
        migrations.AlterModelOptions(
            name='pesticidalproteinprivatedatabase',
            options={'ordering': ('name',), 'verbose_name': 'Private Sequence', 'verbose_name_plural': 'Private Sequences'},
        ),
        migrations.AlterModelOptions(
            name='proteindetail',
            options={'ordering': ('accession',), 'verbose_name': 'Three domain detail', 'verbose_name_plural': 'Three domain details'},
        ),
        migrations.AlterModelOptions(
            name='structuredatabase',
            options={'ordering': ('name',), 'verbose_name': 'Structure Information', 'verbose_name_plural': 'Structure Database'},
        ),
    ]
