# Generated by Django 2.2.6 on 2020-08-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200820_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidalproteinprivatedatabase',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pesticidalproteinprivatedatabase',
            name='private',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
