# Generated by Django 2.2 on 2020-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20201029_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='chimeric',
            field=models.CharField(choices=[('false', 'False'), ('true', 'True')], max_length=1),
        ),
    ]
