# Generated by Django 3.1.3 on 2021-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20210603_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredatabase',
            name='doi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
