# Generated by Django 2.2 on 2020-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20201029_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='chimeric',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=1),
        ),
    ]
