# Generated by Django 2.2.6 on 2020-08-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200820_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteindetail',
            name='sequence',
        ),
    ]
