# Generated by Django 3.1.4 on 2021-01-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20201217_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='modified',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=100),
        ),
    ]
