# Generated by Django 2.2 on 2020-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20201029_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='accession',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='chimeric',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='structuredatabase',
            name='pubmedid',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
