# Generated by Django 2.2.6 on 2020-09-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_proteindetail_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesticidalproteindatabase',
            name='pdbcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
