# Generated by Django 3.1.3 on 2020-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20201029_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuredatabase',
            name='chimeric',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
