# Generated by Django 3.1.4 on 2021-01-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustalanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeresultfiles',
            options={'verbose_name': 'Store result file', 'verbose_name_plural': 'Store results files'},
        ),
    ]
