# Generated by Django 3.1.4 on 2020-12-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittersname', models.CharField(blank=True, max_length=25, null=True)),
                ('submittersemail', models.EmailField(max_length=70, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittersname', models.CharField(blank=True, max_length=25, null=True)),
                ('submittersemail', models.EmailField(max_length=70, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('sequence', models.TextField(null=True)),
                ('bacterium', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('bacterium_textbox', models.CharField(blank=True, max_length=250, null=True)),
                ('taxonid', models.CharField(blank=True, max_length=25, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('partnerprotein', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('partnerprotein_textbox', models.CharField(blank=True, max_length=250, null=True)),
                ('toxicto', models.CharField(blank=True, max_length=250)),
                ('nontoxic', models.CharField(blank=True, max_length=250)),
                ('dnasequence', models.TextField(null=True)),
                ('pdbcode', models.CharField(blank=True, max_length=10)),
                ('publication', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('alignresults', models.TextField(blank=True, null=True)),
                ('predict_name', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('user_provided_proteinname', models.CharField(blank=True, max_length=105)),
                ('admin_user', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittersname', models.CharField(blank=True, max_length=25, null=True)),
                ('submittersemail', models.EmailField(max_length=70, null=True)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('sequence', models.TextField(null=True)),
                ('bacterium', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('bacterium_textbox', models.CharField(blank=True, max_length=250, null=True)),
                ('taxonid', models.CharField(blank=True, max_length=25, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('accession', models.CharField(blank=True, max_length=25)),
                ('partnerprotein', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('partnerprotein_textbox', models.CharField(blank=True, max_length=250, null=True)),
                ('toxicto', models.CharField(blank=True, max_length=250)),
                ('nontoxic', models.CharField(blank=True, max_length=250)),
                ('dnasequence', models.TextField(null=True)),
                ('pdbcode', models.CharField(blank=True, max_length=10)),
                ('publication', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('alignresults', models.TextField(blank=True, null=True)),
                ('predict_name', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('uploaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded')),
                ('user_provided_proteinname', models.CharField(blank=True, max_length=105)),
                ('admin_user', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded',),
                'abstract': False,
            },
        ),
    ]
