# Generated by Django 2.2.6 on 2020-06-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='alignresults',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='predict_name',
        ),
    ]
