# Generated by Django 2.2.6 on 2020-08-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BacteriaTaxonID',
        ),
    ]
