# Generated by Django 3.1.4 on 2020-12-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='published',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='edited_on',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='published',
        ),
    ]
