# Generated by Django 3.1.4 on 2020-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Protein Name'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='sequence',
            field=models.TextField(null=True, verbose_name='Protein Sequence'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Protein Name'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='sequence',
            field=models.TextField(null=True, verbose_name='Protein Sequence'),
        ),
    ]
