# Generated by Django 2.2.6 on 2019-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
