# Generated by Django 3.1.4 on 2020-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0002_auto_20201214_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
