# Generated by Django 2.2.6 on 2020-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0002_auto_20200602_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='alignresults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='predict_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
