# Generated by Django 2.2.6 on 2020-08-20 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0002_delete_bacteriataxonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='uploaded',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Uploaded'),
        ),
    ]
