# Generated by Django 3.1.3 on 2020-11-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0002_auto_20201123_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ('-uploaded',)},
        ),
        migrations.AlterModelOptions(
            name='usersubmission',
            options={'ordering': ('-uploaded',)},
        ),
    ]
