# Generated by Django 3.1.4 on 2020-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0002_auto_20201209_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='accession',
            field=models.CharField(blank=True, max_length=25, verbose_name='NCBI accession number'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='accession',
            field=models.CharField(blank=True, max_length=25, verbose_name='NCBI accession number'),
        ),
    ]
