# Generated by Django 2.2 on 2020-10-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0003_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usersubmission',
            options={},
        ),
        migrations.AlterModelTable(
            name='archive',
            table='archive',
        ),
        migrations.AlterModelTable(
            name='usersubmission',
            table='usersubmission',
        ),
    ]
