# Generated by Django 3.1.4 on 2020-12-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0003_auto_20201209_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='User comments'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='User comments'),
        ),
    ]
