# Generated by Django 2.2.6 on 2020-08-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0004_auto_20200820_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='date',
        ),
    ]
