# Generated by Django 2.2 on 2020-10-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0004_auto_20201021_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ('uploaded',)},
        ),
        migrations.AlterModelOptions(
            name='usersubmission',
            options={'ordering': ('uploaded',)},
        ),
        migrations.AlterModelTable(
            name='archive',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usersubmission',
            table=None,
        ),
    ]
