# Generated by Django 3.1.4 on 2020-12-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0004_auto_20201215_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='alignresults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='alignresults',
            field=models.TextField(blank=True, null=True),
        ),
    ]
