# Generated by Django 2.2.6 on 2020-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0005_remove_usersubmission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='terms_conditions',
            field=models.BooleanField(null=True),
        ),
    ]
