# Generated by Django 3.1.4 on 2020-12-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0005_auto_20201215_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendemail',
            old_name='name',
            new_name='accession',
        ),
    ]
