# Generated by Django 3.1.4 on 2021-01-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0006_auto_20201217_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditentry',
            options={'verbose_name': 'Audit Entry', 'verbose_name_plural': 'Audit entries'},
        ),
    ]
