# Generated by Django 2.2.6 on 2020-09-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0006_usersubmission_terms_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittersname', models.CharField(blank=True, max_length=25, null=True)),
                ('submittersemail', models.EmailField(max_length=70, null=True)),
                ('proteinname', models.CharField(blank=True, max_length=25, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
