# Generated by Django 2.2.6 on 2020-09-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namingalgorithm', '0007_send_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='send_email',
            new_name='SendEmail',
        ),
    ]
